# Generated by Django 3.1.7 on 2021-03-25 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscriberID', models.IntegerField()),
                ('requestdate', models.DateField()),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('motifofcancellation', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='premium',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='TransferredSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transferID', models.IntegerField()),
                ('transferfrom', models.TextField()),
                ('transferto', models.TextField()),
                ('requestdate', models.DateField()),
                ('transferdate', models.DateField()),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.AddField(
            model_name='subscriber',
            name='servicecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.service'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscriptiontypecode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriptiontype'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.userinfo'),
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('nativecountry', models.CharField(max_length=50)),
                ('citizenship', models.CharField(max_length=50)),
                ('isdelegate', models.BooleanField()),
                ('organizationcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.organization')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('officecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.office')),
                ('subscriberID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subscriber')),
            ],
        ),
    ]
